/**
  ******************************************************************************
  * @file           : test_flashsession.cpp
  * @brief          : QTest harness for the FlashSession state machine.
  *
  * Exercises every transition + every failure mode without touching real
  * USB. The session's HidDevice pointer is left null (the session itself
  * never dereferences it; only the DeviceTransitionWatcher uses it, and
  * the watcher's ctor short-circuits null HID).
  *
  * Build:
  *   qmake test_flashsession.pro && mingw32-make
  *   ./test_flashsession.exe
  ******************************************************************************
  */

#include <QtTest/QtTest>
#include <QSignalSpy>
#include <QTemporaryFile>
#include <QObject>

#include "flash/flashsession.h"
#include "flash/devicetransitionwatcher.h"
#include "hiddevice.h"

/* moc_hiddevice.cpp (generated by qmake's HEADERS += hiddevice.h)
 * references the public slot HidDevice::processData -- moc emits a
 * dispatch entry that takes the function's address. The real
 * implementation lives in hiddevice.cpp which the test doesn't compile
 * (it would drag in hidapi + windows-specific transitive deps). Provide
 * an empty stub so the linker resolves; the test never instantiates
 * HidDevice, so the body is never executed. */
void HidDevice::processData() {}

class TestFlashSession : public QObject
{
    Q_OBJECT

private slots:
    /* Create a temp .bin file the session will load via QFile. The
     * contents don't matter -- FlashSession only reads them into a
     * QByteArray and passes the pointer through to needsFlashFirmware. */
    void initTestCase();
    void cleanupTestCase();

    /* Happy paths. */
    void happyPath_normalFlash_endsInDone();
    void happyPath_recoveryFlash_endsInDone();
    void happyPath_noAutoRestore_endsInDone();

    /* Backup-stage variants. */
    void backupFailedUserCancels_endsInFailed();
    void backupFailedUserProceeds_advancesToBootloader();
    void cancelDuringBackup_endsInFailed();

    /* Flash-stage error variants. */
    void flashCrcError_endsInFailed();
    void flashSizeError_endsInFailed();
    void flashEraseError_endsInFailed();

    /* Post-flash variants. */
    void appReturnsIncompatible_endsInDoneNoRestore();
    void restoreWriteFails_endsInFailed();

    /* Slice 3: RecoveryPrompt timeout + resume. Marked _data versions
     * cover both Awaiting* states via the same code path. */
    void bootloaderTimeout_entersRecoveryPrompt();
    void bootloaderTimeout_resumeOnArrival_advancesToFlashing();
    void bootloaderTimeout_userAbort_endsInFailed();
    void appTimeout_entersRecoveryPrompt();
    void appTimeout_resumeOnArrival_advancesToRestoring();

private:
    /* Build a Params struct pointing at the temp firmware file. Caller
     * tweaks runBackup / triggerBootloader / autoRestore as needed. */
    FlashSession::Params makeParams() const;

    /* Walk a fresh session through to a specific state via the same
     * slot calls the production code path would. Returns the live
     * session (caller owns; tests release via the session's parent). */
    FlashSession *walkTo(FlashSession::State target);

    QString m_firmwarePath;
    QTemporaryFile *m_tempBin = nullptr;
};

/* Must match the global.h anonymous enum that HidDevice::flashStatus
 * actually emits -- NOT the raw bootloader wire codes (0xF000-family).
 * Tests previously used the wire codes and passed because flashsession
 * also used the wire codes; both were wrong, masking the real bug
 * where any IN_PROCESS=99 emission fell into "unknown error" default. */
namespace {
constexpr int kFlashFinished   = 0;   // global.h FINISHED
constexpr int kFlashSizeError  = 1;   // global.h SIZE_ERROR
constexpr int kFlashCrcError   = 2;   // global.h CRC_ERROR
constexpr int kFlashEraseError = 3;   // global.h ERASE_ERROR
constexpr int kFlashInProcess  = 99;  // global.h IN_PROCESS
}

/* ========================================================================
 *  Fixture / utilities
 * ====================================================================== */

void TestFlashSession::initTestCase()
{
    m_tempBin = new QTemporaryFile(this);
    m_tempBin->setAutoRemove(true);
    QVERIFY(m_tempBin->open());
    /* Some non-empty payload so QFile::open + readAll() returns bytes. */
    QByteArray junk(1024, char(0xAB));
    m_tempBin->write(junk);
    m_tempBin->flush();
    m_firmwarePath = m_tempBin->fileName();
}

void TestFlashSession::cleanupTestCase()
{
    /* QTemporaryFile auto-removes on destruction; parent owns. */
}

FlashSession::Params TestFlashSession::makeParams() const
{
    FlashSession::Params p;
    p.firmwarePath          = m_firmwarePath;
    p.runBackup             = true;
    p.triggerBootloader     = true;
    p.autoRestoreAfterFlash = true;
    p.targetFwVersion       = 0x0020;
    return p;
}

FlashSession *TestFlashSession::walkTo(FlashSession::State target)
{
    auto *s = new FlashSession(/* hid */ nullptr, this);
    auto p = makeParams();
    /* QVERIFY macros return void; this helper returns FlashSession*.
     * Trust start() to succeed since we control the params; the production
     * code path treats start() failure as a Failed terminal state, and
     * downstream slot calls on a Failed session are no-ops -- so even if
     * start failed here, the assertion would surface as a state mismatch
     * in the caller's QCOMPARE rather than as a silent test pass. */
    (void)s->start(p);
    if (target == FlashSession::State::BackingUp) return s;

    /* BackingUp -> TriggeringBootloader/AwaitingBootloaderEnum */
    s->onBackupSaved(QStringLiteral("/tmp/backup.cfg"));
    if (target == FlashSession::State::TriggeringBootloader ||
        target == FlashSession::State::AwaitingBootloaderEnum) {
        return s;
    }

    /* AwaitingBootloaderEnum -> Flashing */
    s->onFlasherFound(true);
    if (target == FlashSession::State::Flashing) return s;

    /* Flashing -> AwaitingAppEnum */
    s->onFlashStatus(kFlashFinished, 1024, 1024);
    if (target == FlashSession::State::AwaitingAppEnum) return s;

    /* AwaitingAppEnum -> Restoring */
    s->onParamsPacketReceived(true);
    if (target == FlashSession::State::Restoring) return s;

    /* Restoring -> Done */
    s->onConfigSent(true);
    return s;
}

/* ========================================================================
 *  Happy paths
 * ====================================================================== */

void TestFlashSession::happyPath_normalFlash_endsInDone()
{
    FlashSession s(nullptr, this);
    QSignalSpy stateSpy(&s, &FlashSession::stateChanged);
    QSignalSpy finishedSpy(&s, &FlashSession::finished);

    QVERIFY(s.start(makeParams()));
    QCOMPARE(s.state(), FlashSession::State::BackingUp);

    s.onBackupSaved("/tmp/backup.cfg");
    QCOMPARE(s.state(), FlashSession::State::AwaitingBootloaderEnum);

    s.onFlasherFound(true);
    QCOMPARE(s.state(), FlashSession::State::Flashing);

    s.onFlashStatus(kFlashFinished, 1024, 1024);
    QCOMPARE(s.state(), FlashSession::State::AwaitingAppEnum);

    s.onParamsPacketReceived(true);
    QCOMPARE(s.state(), FlashSession::State::Restoring);

    s.onConfigSent(true);
    QCOMPARE(s.state(), FlashSession::State::Done);

    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), true);
}

void TestFlashSession::happyPath_recoveryFlash_endsInDone()
{
    FlashSession s(nullptr, this);
    QSignalSpy finishedSpy(&s, &FlashSession::finished);

    auto p = makeParams();
    p.runBackup             = false;
    p.triggerBootloader     = false;  /* device already in BL */
    p.autoRestoreAfterFlash = false;  /* recovery: nothing to restore */
    QVERIFY(s.start(p));
    QCOMPARE(s.state(), FlashSession::State::Flashing);

    s.onFlashStatus(kFlashFinished, 1024, 1024);
    /* Even for recovery flash we wait for the device to come back, so
     * a freshly-flashed-but-bricked firmware doesn't get reported as
     * "Flash complete". The session lands in AwaitingAppEnum. */
    QCOMPARE(s.state(), FlashSession::State::AwaitingAppEnum);

    /* Simulate the device booting and announcing itself. With
     * autoRestoreAfterFlash=false the session walks straight to Done. */
    s.onParamsPacketReceived(true);
    QCOMPARE(s.state(), FlashSession::State::Done);
    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), true);
}

void TestFlashSession::happyPath_noAutoRestore_endsInDone()
{
    FlashSession s(nullptr, this);
    auto p = makeParams();
    p.autoRestoreAfterFlash = false;
    QVERIFY(s.start(p));
    s.onBackupSaved("/tmp/b.cfg");
    s.onFlasherFound(true);
    s.onFlashStatus(kFlashFinished, 1024, 1024);
    QCOMPARE(s.state(), FlashSession::State::AwaitingAppEnum);
    s.onParamsPacketReceived(true);
    /* autoRestoreAfterFlash=false: terminal Done after app comes back. */
    QCOMPARE(s.state(), FlashSession::State::Done);
}

/* ========================================================================
 *  Backup-stage variants
 * ====================================================================== */

void TestFlashSession::backupFailedUserCancels_endsInFailed()
{
    FlashSession s(nullptr, this);
    QSignalSpy finishedSpy(&s, &FlashSession::finished);

    QVERIFY(s.start(makeParams()));
    s.onConfigReceived(false);                 /* Read failed */
    s.onUserAcceptedNoBackup(false);           /* user said cancel */
    QCOMPARE(s.state(), FlashSession::State::Failed);
    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), false);
}

void TestFlashSession::backupFailedUserProceeds_advancesToBootloader()
{
    FlashSession s(nullptr, this);
    QVERIFY(s.start(makeParams()));
    s.onConfigReceived(false);
    s.onUserAcceptedNoBackup(true);
    QCOMPARE(s.state(), FlashSession::State::AwaitingBootloaderEnum);
}

void TestFlashSession::cancelDuringBackup_endsInFailed()
{
    FlashSession s(nullptr, this);
    QSignalSpy finishedSpy(&s, &FlashSession::finished);
    QVERIFY(s.start(makeParams()));
    s.cancelDuringBackup();
    QCOMPARE(s.state(), FlashSession::State::Failed);
    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), false);
}

/* ========================================================================
 *  Flash-stage error variants
 * ====================================================================== */

void TestFlashSession::flashCrcError_endsInFailed()
{
    auto *s = walkTo(FlashSession::State::Flashing);
    QSignalSpy finishedSpy(s, &FlashSession::finished);
    s->onFlashStatus(kFlashCrcError, 512, 1024);
    QCOMPARE(s->state(), FlashSession::State::Failed);
    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), false);
}

void TestFlashSession::flashSizeError_endsInFailed()
{
    auto *s = walkTo(FlashSession::State::Flashing);
    s->onFlashStatus(kFlashSizeError, 0, 1024);
    QCOMPARE(s->state(), FlashSession::State::Failed);
}

void TestFlashSession::flashEraseError_endsInFailed()
{
    auto *s = walkTo(FlashSession::State::Flashing);
    s->onFlashStatus(kFlashEraseError, 0, 1024);
    QCOMPARE(s->state(), FlashSession::State::Failed);
}

/* ========================================================================
 *  Post-flash variants
 * ====================================================================== */

void TestFlashSession::appReturnsIncompatible_endsInDoneNoRestore()
{
    auto *s = walkTo(FlashSession::State::AwaitingAppEnum);
    QSignalSpy finishedSpy(s, &FlashSession::finished);
    s->onParamsPacketReceived(false);          /* incompatible firmware */
    /* The flash succeeded; auto-restore is skipped because the
     * configurator can't speak to the new wire format. */
    QCOMPARE(s->state(), FlashSession::State::Done);
    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), true);
}

void TestFlashSession::restoreWriteFails_endsInFailed()
{
    auto *s = walkTo(FlashSession::State::Restoring);
    QSignalSpy finishedSpy(s, &FlashSession::finished);
    s->onConfigSent(false);
    QCOMPARE(s->state(), FlashSession::State::Failed);
    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), false);
}

/* ========================================================================
 *  Timeout + RecoveryPrompt
 *
 *  The real timeouts are 10 s / 15 s -- too long for a tight test loop.
 *  We don't override them in slice 5; instead we spin the event loop for
 *  the full duration. If this proves too slow we can add an injectable
 *  timeout parameter later; for now treat these as the slow-but-thorough
 *  end of the suite.
 * ====================================================================== */

void TestFlashSession::bootloaderTimeout_entersRecoveryPrompt()
{
    auto *s = walkTo(FlashSession::State::AwaitingBootloaderEnum);
    /* 10s budget + slack. */
    QTRY_COMPARE_WITH_TIMEOUT(s->state(), FlashSession::State::RecoveryPrompt, 11000);
}

void TestFlashSession::bootloaderTimeout_resumeOnArrival_advancesToFlashing()
{
    auto *s = walkTo(FlashSession::State::AwaitingBootloaderEnum);
    QTRY_COMPARE_WITH_TIMEOUT(s->state(), FlashSession::State::RecoveryPrompt, 11000);
    /* Simulate device finally appearing as flasher after the user's
     * unplug+replug. */
    s->onFlasherFound(true);
    QCOMPARE(s->state(), FlashSession::State::Flashing);
}

void TestFlashSession::bootloaderTimeout_userAbort_endsInFailed()
{
    auto *s = walkTo(FlashSession::State::AwaitingBootloaderEnum);
    QTRY_COMPARE_WITH_TIMEOUT(s->state(), FlashSession::State::RecoveryPrompt, 11000);
    QSignalSpy finishedSpy(s, &FlashSession::finished);
    s->abortFromRecovery();
    QCOMPARE(s->state(), FlashSession::State::Failed);
    QCOMPARE(finishedSpy.count(), 1);
    QCOMPARE(finishedSpy.at(0).at(0).toBool(), false);
}

void TestFlashSession::appTimeout_entersRecoveryPrompt()
{
    auto *s = walkTo(FlashSession::State::AwaitingAppEnum);
    /* 15s budget + slack. */
    QTRY_COMPARE_WITH_TIMEOUT(s->state(), FlashSession::State::RecoveryPrompt, 16000);
}

void TestFlashSession::appTimeout_resumeOnArrival_advancesToRestoring()
{
    auto *s = walkTo(FlashSession::State::AwaitingAppEnum);
    QTRY_COMPARE_WITH_TIMEOUT(s->state(), FlashSession::State::RecoveryPrompt, 16000);
    /* Simulate device finally enumerating as the application. */
    s->onParamsPacketReceived(true);
    /* autoRestoreAfterFlash=true (default in makeParams), so Restoring. */
    QCOMPARE(s->state(), FlashSession::State::Restoring);
}

QTEST_MAIN(TestFlashSession)
#include "test_flashsession.moc"
